CNN_suwwan:
  filter_num: 8
  kernel_size: 2

CNN_HU:
  filter_num_cnn: 20
  kernel_size_cnn: 3
  stride_cnn: 1
  filter_num_pooling: 2
  stride_pooling: 2
  drop_out: 0.25
  loss: binary_crossentropy
  lr: 0.0001
  optimizer: Adam
